name: CI
on:
  push:
    branches:
      - 3.x
  pull_request: {}
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        neo4j_version:
          - 3.0.0
          - 3.0.12
          - 3.1.9
          - 3.2.14
          - 3.3.9
          - 3.4.18
          - 3.5.18
        jdbc_driver_version:
          - 3.0.3
          - 3.1.0
          - 3.3.1
          - 3.4.0
          - 3.5.1
        exclude:
          # Neo4j JDBC driver 3.5.1 requires Neo4j 3.1+
          - jdbc_driver_version: 3.5.1
            neo4j_version: 3.0.0
          - jdbc_driver_version: 3.5.1
            neo4j_version: 3.0.12
    steps:
      - uses: actions/checkout@v2
      - name: Cache ~/.m2/repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests on ${{ matrix.os }} | Neo4j v${{ matrix.neo4j_version }}, JDBC v${{ matrix.jdbc_driver_version }}
        shell: bash
        run: |
          if [[ "${{ matrix.neo4j_version }}" == 3.4* || "${{ matrix.neo4j_version }}" == 3.5* ]] ; then
            EXTRA_ARGS='-P!with-jetty-workaround'
          fi
          mvn --quiet --batch-mode --show-version package -D"neo4j.version"=${{ matrix.neo4j_version }} -D"neo4j-jdbc.version"=${{ matrix.jdbc_driver_version }} ${EXTRA_ARGS}
  container-tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        neo4j_version:
          - 3.0.0
          - 3.0.12
          - 3.1.9
          - 3.2.14
          - 3.3.9
          - 3.4.18
          - 3.5.18
        jdbc_driver_version:
          - 3.0.3
          - 3.1.0
          - 3.3.1
          - 3.4.0
          - 3.5.1
        exclude:
          # Neo4j JDBC driver 3.5.1 requires Neo4j 3.1+
          - jdbc_driver_version: 3.5.1
            neo4j_version: 3.0.0
          - jdbc_driver_version: 3.5.1
            neo4j_version: 3.0.12
    steps:
      - uses: actions/checkout@v2
      - name: Cache ~/.m2/repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Containerized tests | Neo4j v${{ matrix.neo4j_version }}, JDBC v${{ matrix.jdbc_driver_version }}
        run: |
          if [[ "${{ matrix.neo4j_version }}" == 3.4* || "${{ matrix.neo4j_version }}" == 3.5* ]] ; then
            EXTRA_ARGS='-P!with-jetty-workaround'
          fi
          mvn --quiet --batch-mode --show-version --also-make --projects liquigraph-core verify -D"neo4j.version"=${{ matrix.neo4j_version }} -D"neo4j-jdbc.version"=${{ matrix.jdbc_driver_version }}
  deploy-snapshot:
    if: github.ref == 'refs/heads/3.x' && github.repository == 'liquigraph/liquigraph'
    needs: container-tests
    runs-on: ubuntu-latest
    env:
      OSSRH_USER: ${{ secrets.OSSRH_USER }}
      OSSRH_PASS: ${{ secrets.OSSRH_PASS }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache ~/.m2/repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Deploy SNAPSHOT to Maven Central
        run: mvn clean deploy -DskipTests --settings ./deploy-settings.xml
